/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * keyGen.java
 *
 * Created on Apr 28, 2011, 9:29:12 PM
 */

/**
 *
 * @author akriti
 *
 */
  import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.Graphics;
public class keyGenTransfer extends javax.swing.JFrame {
	private javax.swing.JButton jButton1;
    //private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    /** Creates new form keyGen */
    public keyGenTransfer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
      //  jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELGAMAL ENCRYPTION SYSTEM");
        addWindowListener(new WindowAdapter(){


            public void windowClosing(WindowEvent evt){//System.exit(0);
            int response = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.YES_OPTION)
            {
            	System.exit(0);
            }
            else //if(response==JOptionPane.NO_OPTION)
            {

				setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
            }
            }
        });


        jButton1.setText("Press to generate keys");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        /*jButton2.setText("Press to get files from the other system");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });*/
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });


        setLayout(null);
        setSize(500,500);
        add(jButton1);
        //add(jButton2);
        add(jButton3);
        jButton1.setBounds(120,160,250,25);
        //jButton2.setBounds(120,160,250,25);
        jButton3.setBounds(120,220,250,25);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
			 NewJFrame1 njf=new NewJFrame1();
        njf.setVisible(true);
        this.setVisible(false);
    }

    /*private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        this.setVisible(false);
        oldKey ok=new oldKey();
        ok.setVisible(true);
    }*/

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        this.setVisible(false);
        otherSystemOptions oso=new otherSystemOptions();
        oso.setVisible(true);
    }

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keyGen().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify

    // End of variables declaration

}
